### ISSUE TITLE
Nxtgn.biz "configuration failed" 

### ISSUE THREAD

**Issue by danieldamdk** [mafredri/asustor-jackett#1]
Thx for thix awesome apg for my the Asustor users.

I am getting an error when i am typing in my creds for the Nextgen searcher. Probaly because the website has change their domain from .info to .biz - is there anywhere in the code to change this?

**Comment by mafredri** [comment]
Glad you're enjoying it, I'll try to push out a new release soon, the project was forked and is currently maintained at https://github.com/Jackett/Jackett. There's a problem with Jackett running under mono 3.x though and it causes Jackett to crash every now and then. I need to rework the init script to expect crashes and restart the service when it does.

**Comment by mafredri** [comment]
I haven't gotten around to finishing Jackett crash detection + restart (or rather properly testing it), but I just pushed the latest version of Jackett that should include the fixes you were hoping for. Sorry it took so long.
