### ISSUE TITLE
APK not working?

### ISSUE THREAD

**Issue by cryptoking-fir3** [mafredri/asustor-jackett#2]
I have just added this APK to my AS5002T however this apk does not appear to work "Unable to connect". Does this have any dependancies and apps required to make this work on the asustor?

**Comment by danieldamdk** [comment]
It is working like a charm on my AS-608T. You have to be running MONO to have Jackett working. Try if that helps.

**Comment by mafredri** [comment]
Mono is the only dependency and should be required by the apk. Which
version have you installed and did you have a previous version installed
before?

**Comment by mafredri** [comment]
@ragtag-fleet I've just published a maintenance release that probably fixes the issue you were having.
